/*
 * Copyright  Michał Młodawski (SimpleMethod)(c) 2020.
 */

package com.simplemethod.cinema.dataDynamoModel;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import java.util.Map;

@DynamoDBTable(tableName = "Cinema_main")
public class CinemaModel {
    String ID;
    Integer hall;
    Long date;
    String movieName;
    String movieDirector;
    int year;
    int lengthInMinutes;
    Map<String, String> seats;
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    @DynamoDBAttribute(attributeName = "ID")
    public String  getID() {
        return ID;
    }

    public void setID(String  ID) {
        this.ID = ID;
    }
    @DynamoDBAttribute
    public Integer getHall() {
        return hall;
    }

    public void setHall(Integer hall) {
        this.hall = hall;
    }
    @DynamoDBAttribute
    public Long getDate() {
        return date;
    }

    public void setDate(Long date) {
        this.date = date;
    }
    @DynamoDBAttribute
    public String getMovieName() {
        return movieName;
    }

    public void setMovieName(String movieName) {
        this.movieName = movieName;
    }
    @DynamoDBAttribute
    public String getMovieDirector() {
        return movieDirector;
    }

    public void setMovieDirector(String movieDirector) {
        this.movieDirector = movieDirector;
    }
    @DynamoDBAttribute
    public int getYear() {
        return year;
    }

    public void setYear(int year) {
        this.year = year;
    }
    @DynamoDBAttribute
    public int getLengthInMinutes() {
        return lengthInMinutes;
    }

    public void setLengthInMinutes(int lengthInMinutes) {
        this.lengthInMinutes = lengthInMinutes;
    }
    @DynamoDBAttribute
    public Map<String, String> getSeats() {
        return seats;
    }

    public void setSeats(Map<String, String> seats) {
        this.seats = seats;
    }

    public CinemaModel(Integer hall, Long date, String movieName, String movieDirector, Integer year, Integer lengthInMinutes, Map<String, String>  seats) {
        this.hall = hall;
        this.date = date;
        this.movieName = movieName;
        this.movieDirector = movieDirector;
        this.year = year;
        this.lengthInMinutes = lengthInMinutes;
        this.seats = seats;
    }

    public CinemaModel() {
    }
}
